// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Titanosoft.EfConfiguration;

namespace Titanosoft.EfConfiguration.Migrations
{
    [DbContext(typeof(ConfigurationContext))]
    [Migration("20170909140347_EfConfigurationDefaultDate")]
    partial class EfConfigurationDefaultDate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Titanosoft.EfConfiguration.ConfigurationValue", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.HasIndex("LastUpdated");

                    b.ToTable("ConfigurationValues","cfg");
                });
#pragma warning restore 612, 618
        }
    }
}
